version: "3.9"

services:
  mysqldb:
    image: mysql:8.0.33
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build:
      context: .
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - .:/home/app
    stdin_open: true
    tty: true

volumes:
  mysql_data:
